targets:
  $default:
    builders:
      angular:
        options:
          #use_legacy_style_encapsulation: false
          fast_boot: true
          #use_new_template_parser: true
      build_web_compilers|entrypoint:
        options:
          dart2js_args:
          - --minify
          - --fast-startup