name: auge_web
version: 0.1.0
description: Objectives and Works
environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  #analyzer: ^0.39.2+1
  #angular: ^6.0.0-alpha+1
  #angular_router: ^2.0.0-alpha+23
  #angular_forms: ^2.1.2
  #angular_components:
  #  path: D:\Levius\angular_components-master\angular_components
  angular: ^6.0.1
  angular_router: ^2.0.0
  angular_forms: ^3.0.0
  angular_components: ^1.0.2
  #angular_components: ^0.14.0-alpha+1
  #angular_components:
    #git:
      #url: git://github.com/s2nventures/angular_components.git
      #path: angular_components
  sass_builder: ^2.1.3
  intl: ^0.16.1
  #intl_translation: ^0.17.6
  #rpc: ^0.6.0
  #rpc:
  #  git:
  #    url: git://github.com/dart-archive/rpc.git
  #    ref: experimental-mirrors-refactor
  #grpc: ^1.0.2
  #protobuf: ^0.10.4
  #crypto: ^2.0.6
  #uuid: ^2.0.2
  image: ^2.1.18
  chartjs: ^0.5.2
  platform_detect: ^1.4.0
  auge_shared:
    path: ../auge_shared/
  #protobuf: ^1.0.0
  grpc: ^2.3.0
  quiver: ^2.1.3
  csv: ^4.1.0
  #grpc:
  #  git:
  #    url: git://github.com/grpc/grpc-dart.git
  #    ref: grpc-web
  #grpc:
  #  git:
  #    url: git://github.com/sigurdm/grpc-dart.git
  #    ref: ff07ddeae8dcae519b848a9d869dad9724a3ed42

dev_dependencies:
  build_runner: ^1.10.3
  build_web_compilers: ^2.12.0
  webdriver: ^2.1.2
  #angular_analyzer_plugin: ^1.0.0-alpha+1
  #googleapis: 0.53.0
  #protobuf: ^0.13.11
  #grpc:
  #  git:
  #    url: git://github.com/grpc/grpc-dart.git
  #    ref: grpc-web

dependency_overrides:
  #quiver: 2.1.1
  #test: ^1.6.3
  #protobuf: ^0.14.4
  #intl: ^0.15.0
  #analyzer: ^0.37.0
  #protobuf: ^0.13.12