name: auge_web
version: 0.1.0
description: Autogestão
environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  #protobuf: ^0.10.4
  angular_router: ^2.0.0-alpha+19
  angular: ^5.3.0
  angular_forms: ^2.1.1
  angular_components: ^0.12.0
  sass_builder: ^2.1.2
  intl: ^0.15.7
  #rpc: ^0.6.0
  #rpc:
  #  git:
  #    url: git://github.com/dart-archive/rpc.git
  #    ref: experimental-mirrors-refactor
  #grpc: ^1.0.2
  #protobuf: ^0.10.4
  crypto: ^2.0.6
  uuid: ^2.0.0
  image: ^2.0.4
  chartjs: ^0.5.0
  platform_detect: ^1.3.5

  auge_server:
    path: ../auge_server/

dev_dependencies:
  build_runner: ^1.2.3
  build_web_compilers: ^1.2.0
  webdriver: ^2.1.0

dependency_overrides:
  protobuf: ^0.13.9
  grpc:
    git:
      url: git://github.com/grpc/grpc-dart.git
      ref: grpc-web
