name: auge_web
version: 0.0.1
description: Autogestão
environment:
  sdk: '>=2.0.0-dev.3.0 <2.0.0'

dependencies:
  angular_router: ^2.0.0-alpha+14
  angular: ^5.0.0-alpha+15
  angular_forms: ^2.0.0-alpha+7
  angular_components: ^0.9.0-alpha+15
  angular_compiler: ^0.4.0-alpha+15
  intl: ^0.15.6
  rpc: ^0.5.10
  #postgres: ^1.0.0-beta.1
  sass_builder: ^2.0.2
  crypto: ^2.0.2+1
  #uuid: ^1.0.0
  image: ^2.0.4
  front_end: ^0.1.2
  auge_shared:
    path: ../auge_shared/

dev_dependencies:
  build_runner: ^0.9.0
  build_web_compilers: ^0.4.0+4
  webdriver: ^2.0.0-beta+1

dependency_overrides:
  #build_config: ^0.2.6