name: auge_web
version: 0.0.1
description: Autogestão
environment:
  sdk: '>=2.0.0-dev.3.0 <3.0.0'

dependencies:
  angular_router: ^2.0.0-alpha+19
  angular: ^5.0.0
  angular_forms: ^2.0.0
  angular_components: ^0.9.0
  sass_builder: ^2.1.1
  intl: ^0.15.7
  rpc: ^0.6.0
  crypto: ^2.0.6
  uuid: ^1.0.1
  image: ^2.0.4
  auge_server:
    path: ../auge_server/

dev_dependencies:
  build_runner: ^0.10.1
  build_web_compilers: ^0.4.1
  webdriver: ^2.0.0

dependency_overrides:
  #build_config: ^0.2.6